#!/usr/bin/env bash
# -> /opt/pto/cutover-migrate-db.sh   (chmod 750, owned by deploy)
#
# Copy this app's Supabase `public` schema onto this box's Postgres.
#
#   /opt/pto/cutover-migrate-db.sh --rehearse     dry run into pto_rehearsal
#   I_HAVE_STOPPED_CLOUD_RUN=yes \
#     /opt/pto/cutover-migrate-db.sh              the real thing, into pto
#
# ---------------------------------------------------------------------------
# READ THIS BEFORE THE REAL RUN.
#
# Cloud Run and this box currently share one Supabase database. That is what
# makes running both at once safe. The moment this app points at a local
# database, the two deployments stop sharing state: whatever Cloud Run writes
# afterwards is invisible here, and vice versa. There is no merge back.
#
# So the real run is only correct once Cloud Run has stopped serving:
#   gcloud run services update product-testing-os-4 --region europe-west1 \
#     --project sinuous-bedrock-347205 --ingress=internal
#   gcloud scheduler jobs pause product-testing-os-social-agent \
#     --location europe-west1 --project sinuous-bedrock-347205
#
# Anything written to Supabase after the dump begins is NOT carried over.
# Rehearse first; the rehearsal is free and tells you how long the real one
# takes.
# ---------------------------------------------------------------------------
#
# Safe to abort: it only ever READS Supabase, and refuses to overwrite a target
# database that already holds tables.
set -euo pipefail

MODE="${1:-}"
case "$MODE" in
  --rehearse) TARGET_DB=pto_rehearsal ;;
  "")         TARGET_DB=pto ;;
  *) echo "usage: $0 [--rehearse]" >&2; exit 2 ;;
esac

if [ "$TARGET_DB" = "pto" ] && [ "${I_HAVE_STOPPED_CLOUD_RUN:-}" != "yes" ]; then
  cat >&2 <<'MSG'
✗ refusing to migrate into the live target database.

  Cloud Run still shares this database. Migrating while it serves traffic
  splits your data in two with no way to merge it back.

  Rehearse instead:      /opt/pto/cutover-migrate-db.sh --rehearse

  Or, once Cloud Run is genuinely stopped (see the header of this script):
      I_HAVE_STOPPED_CLOUD_RUN=yes /opt/pto/cutover-migrate-db.sh
MSG
  exit 1
fi

cd /opt/postgres
PGPW="$(cat /opt/postgres/.superuser_password)"

psu()  { docker compose exec -T -e PGPASSWORD="$PGPW" postgres psql -U postgres -v ON_ERROR_STOP=1 "$@" </dev/null; }
pgsh() { docker compose exec -T -e PGPASSWORD="$PGPW" -e SRC="$SRC" postgres sh -c "$1" </dev/null; }

# `tr -d \r` is not decoration. app.env is generated by pull-env.sh, which is
# normally run from Windows, where Python's print() emits CRLF. Docker Compose
# strips those when it parses env_file, so the app is fine and the problem is
# invisible there — but this reads the file directly, and a trailing \r makes
# the dbname "postgres\r", which fails as `database "postgres" does not exist`.
SRC="$(grep -m1 '^DATABASE_URL=' /opt/pto/app.env | cut -d= -f2- | tr -d '\r')"
[ -n "$SRC" ] || { echo "✗ DATABASE_URL not found in /opt/pto/app.env" >&2; exit 1; }
# Supabase's pooler on 6543 is TRANSACTION mode, which pg_dump cannot use: it
# needs a session (SET, cursors, a repeatable-read snapshot). 5432 on the same
# host is SESSION mode. This app already uses the direct host, but a future
# edit could paste a pooler URL in.
SRC="${SRC/:6543/:5432}"
SRC="${SRC%%\?*}"

DUMP="/backups/pto_${TARGET_DB}.dump"

echo "############ product-testing-os: database migration ############"
echo "target database : ${TARGET_DB}"
[ "$TARGET_DB" = "pto_rehearsal" ] && echo "mode            : REHEARSAL (nothing switches over)"
date -u +'start           : %Y-%m-%d %H:%M:%SZ'
echo

# Refuse to clobber a database that already has data.
existing="$(psu -tAd "$TARGET_DB" -c 'select count(*) from pg_stat_user_tables' 2>/dev/null || echo 0)"
existing="$(echo "$existing" | tr -d '[:space:]')"
if [ "${existing:-0}" != "0" ]; then
  echo "!! ${TARGET_DB} already contains ${existing} tables — refusing to overwrite." >&2
  echo "   Drop it deliberately first if this is a re-run:" >&2
  echo "     docker compose -f /opt/postgres/compose.yaml exec postgres \\" >&2
  echo "       psql -U postgres -c 'drop database ${TARGET_DB};'" >&2
  echo "     docker compose -f /opt/postgres/compose.yaml exec postgres \\" >&2
  echo "       psql -U postgres -c 'create database ${TARGET_DB} owner pto;'" >&2
  exit 1
fi

echo "-- dump (public schema only; Supabase's auth/storage/realtime schemas"
echo "   belong to Supabase, not to this app, and are all empty here) --"
time pgsh "pg_dump \"\$SRC\" --format=custom --compress=6 --schema=public \
  --no-owner --no-privileges --no-comments --file=${DUMP}"
pgsh "ls -lh ${DUMP} | awk '{print \"   dump size: \" \$5}'"

echo
echo "-- restore --"
# The dump carries "CREATE SCHEMA public", which every Postgres 15+ database
# already has, so a plain restore dies on its first statement. Filter that one
# TOC entry rather than dropping --exit-on-error: a genuine failure must still
# stop the restore instead of leaving a half-populated database.
pgsh "pg_restore -l ${DUMP} | grep -v ' SCHEMA - public ' > ${DUMP}.toc"
time docker compose exec -T -e PGPASSWORD="$PGPW" postgres \
  pg_restore -U postgres -d "$TARGET_DB" --no-owner --no-privileges \
  --jobs=4 --exit-on-error --use-list="${DUMP}.toc" "$DUMP" </dev/null

echo
echo "-- transfer ownership to the app role --"
# The restore ran as superuser, so every object is owned by `postgres`. GRANTs
# are not enough: this app calls Base.metadata.create_all() at IMPORT time in
# five modules, and only the OWNER may run that DDL. Without this the first
# boot dies with "must be owner of table ...".
#
# `reassign owned by postgres to pto` does NOT work — Postgres refuses to
# reassign objects owned by the bootstrap superuser — so walk the catalog.
psu -d "$TARGET_DB" -qc "
  alter schema public owner to pto;
  do \$\$
  declare r record;
  begin
    for r in select tablename from pg_tables where schemaname = 'public' loop
      execute format('alter table public.%I owner to pto', r.tablename);
    end loop;
    for r in select sequencename from pg_sequences where schemaname = 'public' loop
      execute format('alter sequence public.%I owner to pto', r.sequencename);
    end loop;
    for r in select viewname from pg_views where schemaname = 'public' loop
      execute format('alter view public.%I owner to pto', r.viewname);
    end loop;
  end \$\$;
"
notowned="$(psu -tAd "$TARGET_DB" -c "select count(*) from pg_tables where schemaname='public' and tableowner <> 'pto'" | tr -d '[:space:]')"
if [ "${notowned:-1}" != "0" ]; then
  echo "!! ${notowned} table(s) are still not owned by 'pto'." >&2
  echo "   The app runs DDL at import and will fail to boot. Fix before switching." >&2
  exit 1
fi
echo "   all objects owned by 'pto'"

echo
echo "-- verify row counts against source --"
# Table list comes from the SOURCE, not a hardcoded list, so a table added
# since this script was written cannot be silently skipped.
TABLES="$(pgsh "psql \"\$SRC\" -tAc \"select tablename from pg_tables where schemaname='public' order by 1\"" | tr -d '\r')"
mismatch=0
for t in $TABLES; do
  s="$(pgsh "psql \"\$SRC\" -tAc 'select count(*) from public.\"${t}\"'" 2>/dev/null | tr -d '[:space:]')"
  d="$(psu -tAd "$TARGET_DB" -c "select count(*) from public.\"${t}\"" 2>/dev/null | tr -d '[:space:]')"
  if [ "$s" = "$d" ]; then
    printf '   %-32s %12s  OK\n' "$t" "$s"
  else
    printf '   %-32s src=%s dst=%s  *** MISMATCH ***\n' "$t" "$s" "$d"
    mismatch=1
  fi
done

if [ "$mismatch" != "0" ]; then
  echo >&2
  if [ "$TARGET_DB" = "pto_rehearsal" ]; then
    echo "   Row counts differ — EXPECTED during a rehearsal, because Cloud Run is" >&2
    echo "   still writing to Supabase while the dump runs. What matters here is" >&2
    echo "   that the dump, restore and ownership steps all completed." >&2
  else
    echo "!! Row counts differ on the REAL run." >&2
    echo "   If Cloud Run is genuinely stopped this is a real failure — do NOT" >&2
    echo "   switch the app over. If traffic was still live, the source moved" >&2
    echo "   under the dump: stop it properly, drop the target, and re-run." >&2
    exit 1
  fi
fi

echo
psu -d "$TARGET_DB" -c "select pg_size_pretty(pg_database_size('${TARGET_DB}')) as restored_size;"
echo "   ANALYZE (so the planner has stats before first real traffic)"
psu -d "$TARGET_DB" -qc "analyze;"

date -u +'done            : %Y-%m-%d %H:%M:%SZ'
echo
if [ "$TARGET_DB" = "pto_rehearsal" ]; then
  echo "✓ REHEARSAL complete. Nothing was switched; the app still uses Supabase."
  echo "  Drop the rehearsal copy when you are done inspecting it:"
  echo "    docker compose -f /opt/postgres/compose.yaml exec postgres \\"
  echo "      psql -U postgres -c 'drop database pto_rehearsal;'"
else
  echo "✓ Database migrated and verified. Next: /opt/pto/cutover-switch-db.sh"
fi
