options:
  logging: CLOUD_LOGGING_ONLY
substitutions:
  _REGION: europe-west1
  _REPO: pto-repo
  _APP_SVC: pto-app
steps:
# Build combined image
- id: Build App
  name: gcr.io/cloud-builders/docker
  args: ["build","-t","${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPO}/${_APP_SVC}:$SHORT_SHA","."]

# Push combined image
- id: Push App
  name: gcr.io/cloud-builders/docker
  args: ["push","${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPO}/${_APP_SVC}:$SHORT_SHA"]

# Deploy combined service
- id: Deploy App
  name: gcr.io/google.com/cloudsdktool/cloud-sdk
  entrypoint: gcloud
  args:
    ["run","deploy","${_APP_SVC}","--image","${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPO}/${_APP_SVC}:$SHORT_SHA","--region","${_REGION}","--allow-unauthenticated","--port","8080",
     "--set-env-vars","SHOPIFY_SHOP_DOMAIN=${_SHOPIFY_SHOP_DOMAIN},SHOPIFY_API_VERSION=2025-07,META_AD_ACCOUNT_ID=${_META_AD_ACCOUNT_ID},META_PAGE_ID=${_META_PAGE_ID},META_API_VERSION=v23.0,CELERY_BROKER_URL=${_CELERY_URL},CELERY_RESULT_BACKEND=${_CELERY_URL}",
     "--set-secrets","OPENAI_API_KEY=OPENAI_API_KEY:latest,SHOPIFY_ACCESS_TOKEN=SHOPIFY_ACCESS_TOKEN:latest,META_ACCESS_TOKEN=META_ACCESS_TOKEN:latest"]
images:
- ${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPO}/${_APP_SVC}:$SHORT_SHA
